#!/bin/sh
#
#   Startup/shutdown script for the STUN-Server
#
#   Linux chkconfig stuff:
#
#   chkconfig: 35 90 10
#   description: Startup/shutdown script for the STUN-Server
#

# Source function library.
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
else
    exit 0
fi

DAEMON=/usr/local/stund/server
IP1="41.216.220.34"
IP2="41.77.224.34"

prog=stund

start () {
    echo -n $"Starting $prog: "

    # start daemon
    daemon $DAEMON -b -h $IP1 -a $IP2
        RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch /var/lock/subsys/stund
    return $RETVAL
}

stop () {
    # stop daemon
    echo -n $"Stopping $prog: "
    killproc $DAEMON
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f /var/lock/subsys/stund
}

restart() {
    stop
    start
}

case $1 in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    condrestart)
        [ -f /var/lock/subsys/stund ] && restart || :
    ;;
    status)
        status $DAEMON
    ;;
    *)

    echo $"Usage: $prog {start|stop|restart|condrestart|status}"
    exit 1
esac

exit $RETVAL
